name = "Friend Pack"
author = "Nathan McCarty"
version = "0.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cbd9e67485cd43cd346d23ee894205f84bbd31ea46a4cfb66c7ff41986f52aa"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0-beta.2"
