name = "Friend Pack"
author = "Nathan McCarty"
version = "0.3.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac1c1475ef1be76a4f7bafec27a71288189c56278961b58aea0c3c7ea158409d"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"
