name = "Friend Pack"
author = "Nathan McCarty"
version = "0.3.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7cd2754ca14baf25e25676426aee860889163d9763774430b698d75a21ce9493"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"
