name = "Friend Pack"
author = "Nathan McCarty"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03d1339a1ebdf9fa7376674537b9601eb0e771985902b5694157c08a92a8170f"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
