name = "Friend Pack"
author = "Nathan McCarty"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "013e8ccb948d76fb2d562a9aabd47e3c10f983808e241a824757c9507bf73e5d"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"
