name = "Friend Pack"
author = "Nathan McCarty"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c93a1ba460587d61f0402afb7ca9e09e645be00e0571ded672d591ac8803c405"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0-beta.2"
