name = "Friend Pack"
author = "Nathan McCarty"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a481d6dce22b82101f5eab62b2a5e8ab4945481bd09b00c0af6f9e6c3b4ee776"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"
